# Generated by Django 4.1 on 2022-08-24 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.class')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('parent_last_name', models.CharField(max_length=200)),
                ('parent_first_name', models.CharField(max_length=200)),
                ('parent_last_name_kana', models.CharField(max_length=200)),
                ('parent_first_name_kana', models.CharField(max_length=200)),
                ('child_last_name', models.CharField(max_length=200)),
                ('child_first_name', models.CharField(max_length=200)),
                ('child_last_name_kana', models.CharField(max_length=200)),
                ('child_first_name_kana', models.CharField(max_length=200)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.class')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=200)),
                ('status', models.IntegerField()),
                ('reason', models.TextField(blank=True, max_length=1000, null=True)),
                ('reply', models.TextField(blank=True, max_length=1000, null=True)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.child')),
                ('reply_teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kindergarten.teacher')),
            ],
        ),
    ]
